spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test_system?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
    jackson:
          joda-date-time-format: yyyy-MM-dd HH:mm:ss
          date-format: yyyy-MM-dd HH:mm:ss
          time-zone: GMT+8